JUnit
Digriz87/Java_elementary_VP pull request #12
Opened 2021-12-08 19:31 UTC by Digriz87

2021-12-08 23:52 UTC, msch4ever requested changes
25/100
нужно больше тестов. Нужно называть тесты более читабельно. Не нужно было додумывать логику тестируемых классов (создавать собственные эксепшены) - лишняя работа.

2021-12-08 23:52 UTC, msch4ever commented on src/test/java/ua/pro/hw29/CenturyResolverTest.java
> +    @DisplayName("Should by input is zero with exception")
```suggestion
    @DisplayName("Should throw an exception if input equals to zero")
```

2021-12-08 23:52 UTC, msch4ever commented on src/test/java/ua/pro/hw29/CenturyResolverTest.java
> +    @DisplayName("Should by calculate century")
```suggestion
    @DisplayName("Should calculate century by year")
```

2021-12-08 23:52 UTC, msch4ever commented on src/test/java/ua/pro/hw29/CenturyResolverTest.java
> +    void resolveCenturyInput() throws InputIntIsZeroException {
слишком мало тест кейсов. необходимо проверить как для отрицательных годов, так и для положительных. Нужно проверить вокруг граничных значений типа 1 99 100 101 -1 -99 -100 -101 и просто для обычного года типа 1967

2021-12-08 23:52 UTC, msch4ever commented on src/test/java/ua/pro/hw29/LengthCounterTest.java
> +    static String testStringForCheckingNull;
прекондишн должен быть в тестовом методе, а не в качестве статической переменной

2021-12-08 23:52 UTC, msch4ever commented on src/test/java/ua/pro/hw29/LengthCounterTest.java
> +        lengthCounter.countWordsByLength(testString);
нет нужды перед всеми тестами вызывать тестируемый метод

2021-12-08 23:52 UTC, msch4ever commented on src/test/java/ua/pro/hw29/LengthCounterTest.java
> +
нужны читаемые имена тестов

2021-12-08 23:52 UTC, msch4ever commented on src/test/java/ua/pro/hw29/LengthCounterTest.java
> +    void givenInputIsEmpty() {
нужно также проверить на null инпут

2021-12-08 23:52 UTC, msch4ever commented on src/test/java/ua/pro/hw29/LengthCounterTest.java
> +    void countLengthOfMap() {
нужно так же проверять фактические длины слов в мапе на соответствие ключу в мапе

2021-12-08 23:52 UTC, msch4ever commented on src/test/java/ua/pro/hw29/LengthCounterTest.java
> +class LengthCounterTest {
слишком мало тестов

2021-12-11 00:03 UTC, Digriz87 reviewed
Done

2021-12-12 21:57 UTC, msch4ever requested changes
35, за то, что в числе всего 5х кто вообще взялся умножу оценку на  2:)

2021-12-12 21:57 UTC, msch4ever commented on src/test/java/ua/pro/hw29/CenturyResolverTest.java
> +}
-1 => -1
-100 => -1
-101 => -2
-1999 => -20
-2000 => -20
-2001 => -21
1 => 1
100 =>1
101 => 2
1999 => 20
2000 => 20
2001 => 21


вот такие нужны были тесты. А у тебя полу проверки - негативный ли ответ если год негативный. Такая проверка может быть частью тестов, но остальных граничных значений ты не проверяешь

2021-12-12 21:57 UTC, msch4ever commented on src/test/java/ua/pro/hw29/LengthCounterTest.java
> +    @DisplayName("Should to calculate size of Map")
```suggestion
    @DisplayName("Should create a result map of expected size")
```

2021-12-12 21:57 UTC, msch4ever commented on src/test/java/ua/pro/hw29/LengthCounterTest.java
> +    @DisplayName("Should to showing if input is empty with exception")
```suggestion
    @DisplayName("Should throw an exception if input is empty")
```

2021-12-12 21:57 UTC, msch4ever commented on src/test/java/ua/pro/hw29/LengthCounterTest.java
> +    @DisplayName("Should to showing if input is null with exception")
```suggestion
    @DisplayName("Should throw an exception if input is null")
```

2021-12-12 21:57 UTC, msch4ever commented on src/test/java/ua/pro/hw29/LengthCounterTest.java
> +    @DisplayName("Should to showing if getting String more then size of Map")
не могу понять что тут написано.

2021-12-12 21:57 UTC, msch4ever commented on src/test/java/ua/pro/hw29/LengthCounterTest.java
> +        lengthCounter = new LengthCounter();
у тебя же есть статическая переменная уже проиницализированная

2021-12-12 21:57 UTC, msch4ever commented on src/test/java/ua/pro/hw29/LengthCounterTest.java
> +    }
такой же тест нужен на ситуации, когда в мапе больше одного ключа.
Нет теста на билеберду типа *:?№%;*?:*№?:;*?:*%?;*( №;"№; ;№"; 43234 №;"№;
В тестах нужно импровизировать.

2021-12-12 22:37 UTC, merged